### ISSUE TITLE
Broken test

### ISSUE THREAD

**Issue by sebastian-code** [swappsco/django-qa#20] opened 2016-04-12 16:33 UTC
The test _test_create_question_view_one_ on the Test Views module is broken, throws this stacktrace:

```
/home/maestro/Workspace/django-qa/env/lib/python3.4/site-packages/django_markdown/utils.py:47: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return INIT_TEMPLATE.render(ctx)

F....
======================================================================
FAIL: test_create_question_view_one (qa.tests.test_views.TestViews)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maestro/Workspace/django-qa/qa/tests/test_views.py", line 48, in test_create_question_view_one
    self.assertEqual(response.status_code, 302)
AssertionError: 200 != 302
```

**Comment by cdvv7788** [comment] 2016-04-12 21:34
Cannot reproduce it. Can you verify that you have the right versions?

**Comment by sebastian-code** [comment] 2016-04-16 14:21
A freeze from pip
```
Django==1.9.5
django-annoying==0.9.0
django-bootstrap3==7.0.1
django-markdown==0.8.4
django-qa==0.0.18
django-taggit==0.18.1
Markdown==2.6.6
Pillow==3.2.0
```

**Comment by jlariza** [comment] 2016-06-24 12:15
Found the error. Apparently with Django 1.8 the tag field at question model, using taggit, accepted blank tags but with Django 1.9 It is a required field. I just fixed the test, It should be working now. I am closing this issue

**Closed by jlariza** 2016-06-24 12:15 UTC
Labels: bug
